version: "3"

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-06-11T03-13-30Z
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio_data:/data"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123

  # createbuckets:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     /usr/bin/mc config host add myminio http://minio:9000 minio minio123;
  #     /usr/bin/mc ls myminio/saltdata-ml-pipelines &> /dev/null || /usr/bin/mc mb myminio/saltdata-ml-pipelines;
  #     exit 0;
  #     "

volumes:
  minio_data:
    driver: local